version: "3.1"
services:
    www:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./php/api.env
        container_name: www
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html
            - ./php/app.ini:/usr/local/etc/php/php.ini
            - ./php/000-default.conf:/etc/apache2/sites-enabled/default.conf
        environment:
            XDEBUG_CLIENT_HOST: 172.17.0.1
            XDEBUG_CLIENT_PORT: 9001
            XDEBUG_CONFIG: idekey=PHPSTORM
            PHP_IDE_CONFIG: serverName=www-server
        networks:
            - www

volumes:
    persistent: {}

networks:
    www:
